### ISSUE TITLE
Log error

### ISSUE THREAD

**Issue by kiransrdr** [Wenxuan-1119/TransBTS#19]
Traceback (most recent call last):
  File "train.py", line 290, in <module>
    main_worker()
  File "train.py", line 114, in main_worker
    log_args(log_file)
  File "train.py", line 271, in log_args
    fh = logging.FileHandler(log_file)
  File "/usr/lib/python3.7/logging/__init__.py", line 1087, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.7/logging/__init__.py", line 1116, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/Colab Notebooks/Wenxuan_segmentation/log/TransBTS2021-06-26.txt'

**Comment by Shannia-Shan** [comment]
A "log" folder needs to be created.
